site_name: jpsider
repo_url: https://github.com/jpsider/jpsider
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- jpsider Basics:
  - What is jpsider: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Public Functions:
  - Open-ConsoleWindow: Open-ConsoleWindow.md
  - Update-ConsoleTitle: Update-ConsoleTitle.md